Sube2.HelloMvc/Controllers/LessonRegistrationController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Sube1.HelloMVC.Models;

namespace Sube1.HelloMVC.Controllers
{
    public class LessonRegistrationController : Controller
    {
        public IActionResult Index(int id)
        {
            using (var ctx = new OkulDbContext())
            {
                var ogrenciDersler = ctx.OgrenciDersler.Where(od => od.Ogrenciid == id).ToList();
                return View(ogrenciDersler);
            }

        }
        [HttpGet]
        public IActionResult AddLessonRegistration(int id)
        {
            using (var ctx = new OkulDbContext())
            {
                var lst = ctx.Dersler.ToList();
                ViewBag.StudentId = id;
                return View(lst);
            }
        }
        [HttpPost]
        public IActionResult AddLessonRegistration(int ogrenciid, int dersid)
        {
            var ogrenciDers = new OgrenciDers();

            using (var ctx = new OkulDbContext())
            {
                bool exists = ctx.OgrenciDersler.Any(od => od.Ogrenciid == ogrenciid && od.Dersid == dersid);
                if (!exists)
                {
                    ogrenciDers.Dersid = dersid;
                    ogrenciDers.Ogrenciid = ogrenciid;

                    ctx.OgrenciDersler.Add(ogrenciDers);
                    ctx.SaveChanges();
                }
                else
                {                 
                    TempData["ErrorMessage"] = "Bu öğrenci zaten bu derse kayıtlı.";
                }
            }
            return RedirectToAction("AddLessonRegistration", new { id = ogrenciDers.Ogrenciid });
        }



    }
}

Sube2.HelloMvc/Controllers/StudentController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Sube1.HelloMVC.Models;

namespace Sube1.HelloMVC.Controllers
{
    public class StudentController : Controller
    {
        public IActionResult Index()
        {
            using (var ctx = new OkulDbContext())
            {
                var lst = ctx.Ogrenciler.ToList();
                return View(lst);
            }
        }

        [HttpGet]
        public IActionResult AddStudent()
        {
            return View();
        }

        [HttpPost]
        public IActionResult AddStudent(Ogrenci ogrenci)
        {
            if (ogrenci != null)
            {
                using (var ctx = new OkulDbContext())
                { 
                    ctx.Ogrenciler.Add(ogrenci);
                    ctx.SaveChanges();
                }
            }
            return RedirectToAction("Index");
        }
        public IActionResult EditStudent(int id)
        {
            using (var ctx = new OkulDbContext())
            {
                var ogr = ctx.Ogrenciler.Find(id);
                return View(ogr);
            }

        }
        [HttpPost]
        public IActionResult EditStudent(Ogrenci ogrenci)
        {

            if (ogrenci != null)
            {
                using (var ctx = new OkulDbContext())
                {
                    ctx.Entry(ogrenci).State = EntityState.Modified;
                    ctx.SaveChanges();
                }
            }
            return RedirectToAction("Index");
        }
        public IActionResult DeleteStudent(int id)
        {
            using (var ctx = new OkulDbContext())
            {
                ctx.Ogrenciler.Remove(ctx.Ogrenciler.Find(id));
                ctx.SaveChanges();
            }
            return RedirectToAction("Index");
        }
        public IActionResult StudentLessons(int studentId)
        {
            using (var ctx = new OkulDbContext())
            {
                var studentLessons = ctx.OgrenciDersler
                .Where(od => od.Ogrenciid == studentId).Join(ctx.Ogrenciler, od => od.Ogrenciid, o => o.Ogrenciid, (od, o) => new { od, o })
                .Join(ctx.Dersler, od_o => od_o.od.Dersid, d => d.Dersid,
                    (od_o, d) => new StudentLessonViewModel
                    {
                        StudentId = od_o.o.Ogrenciid,
                        StudentName = od_o.o.Ad,
                        StudentSurname = od_o.o.Soyad,
                        LessonId = d.Dersid,
                        LessonName = d.Dersad,
                        LessonCredit = d.Kredi
                    })
                .ToList();

                return View(studentLessons);
            }
        }
    }
}

Sube2.HelloMvc/Views/LessonRegistration/AddLessonRegistration.cshtml
@model IEnumerable<Ders>
@{
    ViewData["Title"] = "AddLessonRegistration";
    var studentId = ViewBag.StudentId;
}
<div class="text-area">
    <h2 style="text-align:center">Öğrenciye Ders Ekleme</h2>
    <a asp-action="StudentLessons" asp-controller="Student" asp-route-studentId="@studentId" class="btn btn-outline-primary">Aldığı Dersler</a>
    <table class="table">
        <thead>
            <tr>
                <th>Ders Id</th>
                <th>Ders Adı</th>
                <th>Ders Kredisi</th>
                <th>İşlemler</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>@item.Dersid</td>
                    <td>@item.Dersad</td>
                    <td>@item.Kredi</td>
                    <td>
                        <form asp-action="AddLessonRegistration" asp-controller="LessonRegistration" method="post">
                            <input type="hidden" name="ogrenciid" value="@studentId" />
                            <input type="hidden" name="dersid" value="@item.Dersid" />
                            <button type="submit" class="btn btn-sm btn-outline-success" onclick="return confirm('Emin Misiniz?')">Ekle</button>
                        </form>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

Sube2.HelloMvc/Views/LessonRegistration/Index.cshtml
@model IEnumerable<OgrenciDers>
@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>
<a asp-action="AddLessonRegistration" asp-controller="LessonRegistration" class=" btn btn-outline-primary">Ders Kaydı</a>

<table class="table">
    <thead>
        <tr>
            <th>Ogrenciid</th>
            <th>Dersid</th>
        </tr>

    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <th>@item.Ogrenciid</th>
                <th>@item.Dersid</th>
                <th><a class="btn btn-sm btn-outline-success" href="/Student/EditStudent/@item.Ogrenciid">Düzenle</a> <a onclick=" return confirm('Emin Misiniz?')" class="btn btn-sm btn-outline-danger" href="/Student/DeleteStudent/@item.Ogrenciid">Sil</a> <a class="btn btn-sm btn-outline-info" href="/LessonRegistration/AddLessonRegistration/@item.Ogrenciid,@item.Dersid">Ders Ekle</a></th>

            </tr>
        }
    </tbody>
</table>